import type { SiteSettingsMerged } from "@/types/site-settings";
import { DEFAULT_HOME_HUB } from "@/lib/site-settings/home-hub-defaults";
import { defaultProgramGuideBase } from "@/lib/site-settings/program-defaults";

const DEFAULT_PROGRAM: SiteSettingsMerged["program"] = {
  navLabel: "프로그램",
  promoLinkLabel: "루틴·용어 정리",
  pageEyebrow: "가이드",
  pageTitle: "운동 프로그램 개요",
  pageLead:
    "벌크·컷 할 때 자주 나오는 말만 골라 넣었어요. 아프거나 병력이 있으면 병원 말이 먼저예요.",
  showBuiltInSections: true,
  prefixMarkdown: "",
  appendixMarkdown: "",
  ...defaultProgramGuideBase(),
};

export const DEFAULT_SITE_SETTINGS = {
  program: DEFAULT_PROGRAM,
  images: {
    headerLogo: {
      src: "",
      alt: "홈",
    },
    hero: {
      src: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=2000&q=82",
      alt: "헬스장, 덤벨이 놓인 벤치",
    },
    coaching: {
      src: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=82",
      alt: "바벨과 웨이트 트레이닝 공간",
    },
    listEmpty: {
      src: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1000&q=78",
      alt: "트레이닝 준비하는 운동 공간",
    },
    authPanel: {
      src: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1600&q=82",
      alt: "밝은 피트니스 룸과 장비",
    },
    dashTile1: {
      src: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80",
      alt: "바벨 트레이닝",
    },
    dashTile2: {
      src: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=80",
      alt: "트레이닝 공간",
    },
    dashTile3: {
      src: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=900&q=80",
      alt: "피트니스 룸",
    },
  },
  copy: {
    appTitle: "운동 기록 · 코칭",
    appDescription: "세트는 계정에 붙어서 저장되고, 코칭은 그걸 보고 짧게 적어 줘요.",
    loginPanel: {
      eyebrow: "JWS",
      title: "기록이 쌓이면 패턴이 보여요",
      description: "폰이 바뀌어도 같은 계정이면 그대로예요. 홈에서 입력하고 아래로 내려가면 목록이랑 코칭이 이어져요.",
    },
    loginCard: {
      eyebrow: "Welcome",
      title: "다시 왔네요",
      subtitle: "이메일이랑 비밀번호 넣고 들어가면 돼요.",
    },
    loginForm: {
      emailLabel: "이메일",
      passwordLabel: "비밀번호",
      submitLabel: "로그인",
      submittingLabel: "잠깐만요…",
      noAccountPrompt: "아직 없어요?",
      signupLinkLabel: "가입하고 시작하기",
    },
    signupPanel: {
      eyebrow: "JWS",
      title: "운동 일기장 하나 만들기",
      description: "세트만 몇 번 저장해도 목록이랑 코멘트가 같이 쌓여요. 적을 건 별로 없어요.",
    },
    signupCard: {
      eyebrow: "Join",
      title: "회원가입",
      subtitle: "인증 메일은 스팸함·프로모션함도 한번 봐 주세요.",
    },
    mainHero: {
      eyebrow: "Today",
      titleLine1: "오늘 세트만 남기고",
      titleLine2: "내일은 오늘보다 편하게",
      subtitle: "저장하면 알아서 올라가요. 입력·목록·코칭 다 이 페이지에 있어요.",
    },
    mainNavSectionLabels: ["기록 넣기", "지난 기록", "코칭"],
    mainDashTileCaptions: ["기록 넣기", "전체 기록", "코칭 보기"],
    webCoachingEyebrow: "Coaching",
    webCoachingTitle: "코칭 한 줄",
    webCoachingHint:
      "저장해 둔 운동을 보고 짧게 코멘트를 붙여요. OpenAI 쓰려면 서버에 API 키랑 COACHING_USE_OPENAI가 있어야 하고, COACHING_CONTENT_URL 넣으면 그 페이지 글도 같이 읽어요.",
    webCoachingButtonLabel: "코멘트 받기",
    listEmptyTitle: "아직 기록이 없어요",
    listEmptySubtitle: "한 줄만 넣어도 여기가 금방 차요.",
    workoutForm: {
      eyebrow: "New",
      title: "오늘 세트",
      subtitle: "적을 건 이것뿐이에요. 저장하면 바로 아래 목록에 붙어요.",
      exerciseLabel: "운동 이름",
      exercisePlaceholder: "예: 벤치 (줄여도 됨)",
      weightLabel: "중량 (kg)",
      repsLabel: "횟수",
      setsLabel: "세트",
      outcomeGroupLabel: "이번 세트",
      outcomeAriaLabel: "잘했는지 여부",
      successLabel: "잘함",
      failLabel: "아쉬움",
      saveButtonLabel: "저장",
      savingButtonLabel: "저장 중…",
      savedToast: "올렸어요.",
    },
    coachingHistoryTitle: "최근 코칭",
    helpCenter: {
      pageTitle: "도움말",
      intro: "기록 넣기 → 목록 보기 → 코칭 순서만 알면 돼요. 아래 FAQ만 봐도 대부분 나와요.",
      contactLine: "더 물어볼 건 운영 메일로 보내 주세요.",
      faqSectionTitle: "자주 묻는 질문",
      faqItems: [
        {
          question: "기록은 어디에 저장되나요?",
          answer:
            "로그인한 계정에 묶여서 Supabase에 올라가요. 다른 폰·PC에서 같은 계정으로 보면 그대로예요.",
        },
        {
          question: "코칭은 어떻게 돌아가요?",
          answer:
            "저장된 운동을 서버가 읽고 짧게 정리해요. OpenAI 쓰려면 관리자가 API 키를 넣어 둬야 해요.",
        },
        {
          question: "비밀번호를 잊었습니다.",
          answer: "설정에서 재설정 메일 받거나, 로그인 화면에 비밀번호 찾기 있으면 그걸 쓰면 돼요.",
        },
        {
          question: "기록을 지울 수 있나요?",
          answer: "목록에서 하나씩 지울 수 있고, 홈에서 전부 지우기도 돼요. 전부 지우기는 돌이킬 수 없어서 신중히 눌러 주세요.",
        },
      ],
    },
    legalPages: {
      termsEyebrow: "약관",
      privacyEyebrow: "개인정보",
      termsTitle: "이용약관",
      termsBody:
        "제1조 (목적)\n이 약관은 이 서비스 쓸 때 지켜야 할 기본만 적어 둔 거예요.\n\n제2조 (서비스)\n운동 기록 저장, 목록 보기, 코칭 같은 기능을 제공해요.\n\n제3조 (이용자의 의무)\n계정은 본인만 쓰고, 남이랑 같이 쓰지 말아 주세요.",
      privacyTitle: "개인정보처리방침",
      privacyBody:
        "1. 수집 항목\n이메일, 운동 기록, 코칭 요청 때 같이 올라가는 요약이 있을 수 있어요.\n\n2. 이용 목적\n서비스 돌리고, 본인 확인하고, 문의 답하는 데 써요.\n\n3. 보관\n계정 지우거나 법에서 정한 기간이 지나면 정리돼요.",
    },
    footer: {
      primaryLine: "운동 기록 · 코칭",
      secondaryLine: "",
      links: [
        { label: "이용약관", href: "/legal/terms" },
        { label: "개인정보", href: "/legal/privacy" },
        { label: "도움말", href: "/help" },
      ],
      copyrightLine: "© {year}",
    },
    loginExtras: {
      adminLinkLabel: "Admin",
    },
    signupForm: {
      emailLabel: "이메일",
      passwordLabel: "비밀번호 (6자 이상 권장)",
      submitLabel: "가입하기",
      submittingLabel: "처리 중…",
      successLineBefore: "가입 요청이 접수됐어요. 메일함을 확인하거나, 바로",
      successLoginCta: "로그인",
      successLineAfter: "해도 돼요.",
      errorGeneric: "가입 처리 중 오류가 났어요. Supabase 환경 변수를 확인해 주세요.",
      footerPrompt: "이미 계정 있어?",
      footerLoginLabel: "로그인",
    },
    mainDashboard: {
      heroCtaTodayCard: "오늘 카드 보기",
      heroPerformanceLinkLabel: "성과",
      summaryTotalLabel: "전체",
      summaryTotalUnit: "건",
      summaryTotalSub: "세트 행",
      summaryWeekLabel: "이번 주",
      summaryWeekUnit: "건",
      summaryWeekSub: "월~일",
      summaryVolumeLabel: "주간 볼륨",
      summaryVolumeUnit: "합",
      summaryVolumeSubFallback: "kg×회×세트",
      summaryVolumeSubTopTemplate: "1위 {exercise}",
      shortcutsSectionTitle: "바로가기",
      shortcutWriteTitle: "오늘 줄 적기",
      shortcutWriteSubtitle: "저장하면 목록에 바로 붙어요",
      shortcutPerformanceTitle: "성과 보기",
      shortcutPerformanceSubtitle: "그래프랑 CSV 다운로드",
      shortcutHelpTitle: "도움말",
      shortcutHelpSubtitle: "FAQ랑 문의 안내",
      emptyStateTitle: "아직 기록이 없어요",
      emptyStateSubtitle: "한 줄부터 쌓아 볼까요?",
      emptyStateCta: "줄 적기",
      clearAllRecordsLabel: "전체 지우기",
      navPageSectionsAriaLabel: "페이지 섹션",
      sectionEyebrowInput: "입력",
      sectionEyebrowList: "기록",
      sectionEyebrowCoach: "코치",
      sectionHintInputBeforeProgram: "저장하면 바로 아래 목록에 붙어요.",
      sectionHintList: "날짜·종목별로 보다가 필요하면 하나씩 지울 수 있어요.",
      sessionCoachRestDay: "오늘은 쉬는 쪽이 맞아 보여요. 가볍게만 하거나 패스해도 돼요.",
      sessionCoachActiveDayTemplate:
        "오늘은 평소의 {percent}%쯤으로 가 볼까요. 세트 사이에는 60~120초 쉬는 걸 추천해요.",
      toastPrOnFormSave: "새 PR이에요! 이 종목 볼륨 최고 기록을 갱신했어요.",
      xpToastLevelUpTemplate: "레벨 {level} 달성! +{xp} XP",
      xpToastPrTemplate: "PR! +{xp} XP",
      xpToastGainTemplate: "+{xp} XP 획득",
      confirmDeleteAllRecords: "이 계정에 저장된 모든 운동 기록을 삭제하시겠습니까? 삭제 후에는 복구할 수 없습니다.",
      confirmDeleteOneRecord: "선택한 기록만 삭제하시겠습니까?",
      recordsCountSuffix: "건",
    },
    appShell: {
      homeAriaLabel: "홈",
      mainNavAriaLabel: "주요 메뉴",
      adminLinkLabel: "운영",
      signOutLabel: "로그아웃",
      homeLogoFallbackAlt: "홈",
      footerFeedbackMail: "문의(메일)",
      footerFeedbackForm: "문의(폼)",
      footerStatusFallback: "장애 시 상태 확인",
    },
    settingsPage: {
      sectionStep: "AC",
      sectionEyebrow: "ACCOUNT",
      title: "계정 설정",
      description: "로그인된 이메일 확인과 비밀번호 재설정을 안내합니다.",
      emailHeading: "이메일",
      passwordHelp:
        "비밀번호를 변경하려면 아래 버튼으로 재설정 메일을 요청하세요. 메일의 링크를 연 뒤 새 비밀번호를 입력합니다.",
      btnSending: "발송 중…",
      btnRequestReset: "비밀번호 재설정 메일 요청",
      msgResetSent: "재설정 링크를 이메일로 보냈습니다. 받은편지함과 스팸함을 확인해 주세요.",
      msgGenericError: "요청을 처리하는 중 오류가 발생했습니다.",
    },
    performancePage: {
      sectionStep: "02",
      eyebrow: "리포트",
      title: "운동 성과 리포트",
      description: "기간별 요약, 차트, 필터, CSV 내려받기를 한 화면에서 제공합니다.",
      countBadgeTemplate: "{count}건",
      searchLabel: "종목 검색",
      searchPlaceholder: "예: 스쿼트",
      dateFromLabel: "시작 날짜",
      dateToLabel: "종료 날짜",
      resetButton: "초기화",
      statSetsLabel: "세트",
      statVolumeLabel: "볼륨 합",
      csvDownloadTemplate: "CSV 내려받기 ({count}건)",
      listPreviewTitle: "목록 미리보기",
      emptyFiltered: "조건에 맞는 기록이 없습니다.",
      outcomeSuccess: "달성",
      outcomeFail: "미달",
      story: {
        reportEyebrow: "한 줄 리포트",
        reportTitle: "이번 주 운동 스토리",
        reportSubtitle: "이번 주 기록을 짧게 풀어 쓴 거예요.",
        summaryEyebrow: "한 줄 요약",
        thisWeekVolumeLabel: "이번 주 볼륨 합",
        lastWeekVolumeLabel: "지난주 볼륨 합",
        weekDeltaLabel: "주간 증감",
        rowCountLabel: "세트 행 수",
        highlightsTitle: "핵심 포인트",
        chartVolumeTitle: "주간 볼륨 그래프",
        chartVolumeSubtitle: "최근 8주 · kg×회×세트 합",
        chartWeekBarTitleTemplate: "{label}주 · {volume}",
        chartActiveDaysBarTitleTemplate: "{label}주 · {activeDays}일",
        chartActiveDaysTitle: "운동한 날",
        chartActiveDaysSubtitle: "같은 기간 · 주당 며칠 왔는지(0~7)",
        chartActiveDaysUnitSuffix: "일",
        section7DayTitle: "최근 7일 볼륨",
        section7DaySubtitle: "요일별로 촘촘히 보는 미세 추세",
      },
      bodyWeight: {
        eyebrow: "체중 추적",
        title: "체중",
        subtitleLocal: "이 브라우저에만 남아요.",
        emptyHint: "기록이 없습니다. 아래에서 추가해 보세요.",
        dateLabel: "날짜",
        weightLabel: "체중 (kg)",
        placeholder: "예: 72.4",
        saveButton: "저장",
        deleteButton: "삭제",
        msgBadDate: "날짜를 확인해 주세요.",
        msgBadRange: "체중은 20~300kg 사이로 입력해 주세요.",
        msgSavedLocal: "이 브라우저에만 저장했어요.",
      },
    },
    helpPageExtras: {
      pageEyebrow: "도움",
      programHintBeforeLink: "스플릿·델로드·RPE 등은",
      moreLinksTitle: "더보기",
      feedbackMailLabel: "피드백·문의(메일)",
      feedbackFormLabel: "피드백·문의(폼)",
      statusFallbackLabel: "장애 시 상태 확인",
    },
    onboarding: {
      errorRoutineMd: "루틴 초안을 불러오지 못했습니다. 홈으로 이동한 뒤 다시 시도해 주세요.",
      eyebrow: "시작 설정",
      title: "프로필에 맞춘 루틴",
      intro: "네 가지 질문에 답하면 주간 루틴 초안을 생성합니다.",
      goalLegend: "1. 운동 목표",
      goalBulk: "벌크업·힘 키우기",
      goalCut: "컷·체지방 줄이기",
      goalMaintain: "유지·건강 관리",
      expLegend: "2. 운동 경력",
      expBeginner: "입문 ~ 1년 차",
      expIntermediate: "1~3년 차",
      expAdvanced: "3년 이상 꾸준히",
      daysLegend: "3. 일주일에 몇 번?",
      daysPerWeekTemplate: "주 {n}회",
      equipmentLegend: "4. 이용 가능한 장비",
      equipmentPlaceholder: "예: 바벨, 스미스, 케이블, 덤벨 2~20kg",
      back: "뒤로",
      next: "다음",
      generating: "초안 생성 중…",
      submit: "루틴 초안 생성",
      savedTitle: "프로필이 저장되었습니다.",
      homeCta: "홈으로 이동",
    },
    billingPages: {
      successTitle: "결제가 완료되었습니다 🎉",
      successBodyHtmlIntro:
        "프리미엄이 활성화되었어요. 이 기기에서는 ",
      successBodyHtmlOutro: " 로 잠금이 풀립니다.",
      successBullet1: "AI 코칭 일일 제한 없이 이어가기",
      successBullet2: "루틴 자동 최적화·주간 리포트",
      successBullet3: "운동 직후 세션 기반 심층 분석 힌트",
      homeLink: "홈으로",
      cancelTitle: "결제가 취소되었습니다",
      cancelSubtitle: "언제든지 다시 시도할 수 있어요.",
      settingsLink: "설정으로",
      billingLegacyTitle: "이 결제 확인 경로는 사용되지 않아요",
      billingLegacyBody:
        "구독·단건 결제는 PortOne(아임포트)으로 진행됩니다. 결제가 끝나면 자동으로 /success 페이지로 이동해요.",
      billingLegacyCtaSuccess: "결제 완료 페이지로",
      billingLegacyCtaSettings: "설정으로",
    },
    workoutSession: {
      flowTagline: "시작 → 하다 → 끝",
      flowStep1: "시작",
      flowStep2: "진행",
      flowStep3: "완료",
      flowAriaLabel: "운동 세션 단계",
      coachModeLabel: "코치 모드",
      coachModeAriaOn: "코치 모드 켜짐",
      coachModeAriaOff: "코치 모드 꺼짐",
      coachModeSrOn: "켜짐",
      coachModeSrOff: "꺼짐",
      workoutModeIdleLabel: "운동 모드",
      coachCueResumeNext: "이제 다음 세트 가도 돼요.",
      toastExerciseRequired: "종목 이름부터 적어줘요",
      coachCueRestTemplate: "휴식 {seconds}초. 됐으면 다음 세트 가요.",
      toastXpLevelTemplate: "레벨 {level}! +{xp} XP",
      toastXpPrTemplate: "PR! +{xp} XP",
      toastXpGainTemplate: "+{xp} XP · 저장 완료",
      notifyEyebrow: "알림",
      prBannerEyebrow: "PR",
      prBannerTitle: "PR 떴다",
      prBannerSubtitle: "이번 세트가 이 종목 볼륨 최댓값 찍었어요.",
      idleStepEyebrow: "1 · 운동 시작",
      startButton: "운동 시작하기",
      idleHintFlow: "세트 입력 → 코치 휴식 → 저장까지 한 화면에서 이어집니다.",
      idleHintCoachOn: "코치 모드 ON: 세트 저장하면 휴식 타이머 돌고, 다음 세트 때 한 줄로 깨워줘요.",
      idleHintCoachOff: "코치 모드 켜면 세트 사이 휴식도 재고, 다음 세트 타이밍도 잡아줘요.",
      activeStepEyebrow: "2 · 운동 진행",
      restRegionAria: "세트 사이 쉬는 시간",
      restEyebrow: "쉬는 시간",
      restTitleTemplate: "휴식 {seconds}초",
      restProgressTemplate: "경과 {elapsed}",
      restRemainingPartTemplate: " · 권장까지 {remaining}",
      restNextOk: "다음 세트 가도 돼요.",
      restLongNudge: "1분 30초 넘게 쉬었어요. 이제 다음 세트 가 볼까요.",
      restNextButton: "다음 세트 가기",
      exerciseLabel: "종목",
      exercisePlaceholder: "예: 스쿼트",
      prevSameEyebrow: "이전 기록 (같은 종목)",
      volumeWord: "볼륨",
      noPrevSameHint: "이 종목 기록 아직 없어요. 첫 세트부터 남겨 보세요.",
      weightLabel: "중량 (kg)",
      weightQuickEntry: "간편 입력",
      weightFineTune: "미세 조정 (kg)",
      repsLabel: "횟수",
      setsLabel: "세트",
      repsQuickEntry: "빠른 입력",
      outcomeSuccess: "성공",
      outcomeFail: "실패",
      saveSet: "세트 저장",
      savingSet: "저장 중…",
      saveBlockedRest: "휴식 중 — 위 버튼 먼저",
      finishSession: "오늘은 여기까지",
      doneStepEyebrow: "3 · 운동 종료",
      doneTitle: "운동 종료",
      doneResultEyebrow: "결과 요약",
      doneSessionLine: "오늘 세션을 마쳤어요.",
      donePrSetsTemplate: "PR 세트 {count}개 — 오늘도 한계 갈아끼웠네요.",
      summarySets: "세트",
      summaryVolume: "볼륨 합",
      summaryPrSets: "PR 세트",
      summaryTime: "시간",
      linkHome: "홈 가기",
    },
    homeHub: DEFAULT_HOME_HUB,
  },
  experience: {
    missedDayHourLocal: 22,
    workoutRestTargetSeconds: 60,
    briefingHighLoadDayMinRows: 7,
    briefingHighLoadDayMinVolume: 900,
    interventionMorningEndHour: 12,
    interventionAfternoonEndHour: 18,
    interventionEveningEndHour: 21,
    navLabels: {
      home: "홈",
      workout: "운동",
      performance: "성과",
      help: "도움말",
      settings: "설정",
    },
  },
} satisfies SiteSettingsMerged;
