import type { SiteHomeHubCopy } from "@/types/site-home-hub-copy";

export const DEFAULT_HOME_HUB: SiteHomeHubCopy = {
  singleAction: {
    eyebrowWhenPlanLocked: "오늘 운동 (고정)",
    eyebrowDefault: "오늘 운동",
    ctaWhenSessionActive: "세션 이어가기",
    ctaWhenDone: "추가로 기록하기",
    ctaStart: "운동 시작하기",
    linkChangePlanOptional: "플랜만 바꾸기 (선택)",
  },
  onboardingBanner: {
    bodyPrefix: "목표와 주당 횟수를 알려 주시면,",
    bodyStrong: "루틴 초안",
    bodySuffix: "을 바로 받을 수 있어요.",
    ctaStart: "시작하기",
    ctaLater: "나중에",
  },
  secondary: {
    sectionEyebrow: "기록 · 분석 · 코치",
  },
  userRibbon: {
    stateIdle: "운동 전",
    stateActive: "운동 중",
    stateCompleted: "운동 완료",
    stateMissed: "운동 미완",
    ariaLabelTemplate: "오늘 운동 상태: {label}",
    messageIdleBefore: "오늘은 아직 기록 전이에요. 아래에서 ",
    messageIdleHighlight: "플랜 고르기 → 운동 들어가기",
    messageIdleAfter: "만 이어가면 돼요.",
    messageActive: "세션 진행 중이에요. 운동 화면으로 돌아가 휴식·세트만 이어서 저장하면 돼요.",
    messageCompleted: "오늘 볼륨이 쌓였어요. 성취·분석은 성과 탭에서 확인해 보세요.",
    messageMissed: "오늘은 아직 세트가 없어요. 짧게라도 한 번 돌리면 스트릭이랑 기록이 이어져요.",
    ctaStartWorkout: "운동 시작하기",
    ctaResumeSession: "세션 이어가기",
    ctaViewAnalysis: "분석 보기",
    ctaQuickStart: "빠른 루틴 시작",
    ctaFindShortRoutine: "짧은 루틴 찾기",
  },
  streakBadges: {
    titleEyebrow: "연속 스택 뱃지",
    streakWord: "연속",
    unlocked: "획득",
    locked: "잠금",
    nextBadgeTemplate: "{next}일 뱃지까지 {remaining}일 남음",
    fullComboLine: "30일 뱃지 풀콤보 달성.",
  },
  noWorkout: {
    phaseMorning: "오전",
    phaseAfternoon: "오후",
    phaseEvening: "저녁",
    phaseNight: "밤",
    eyebrowTodayLine: "오늘 한 줄",
    reasonBadge: "이유",
    routineLinePlanLockedSuffix: " · 플랜 고정됨",
    routineLinePlanOpenSuffix: " · 아래에서 플랜만 정하면 됨",
    nightStreakHint: "한 종목·한 세트만 넣어도 연속은 이어져요.",
    ctaStartNow: "지금 시작하기",
    ctaQuickRoutine: "빠른 루틴 실행",
    programLink: "프로그램 보기",
  },
  todayHero: {
    routineFeedEyebrow: "루틴 피드",
    reasonChip: "이유",
    rulesEngineFootnote: "지금은 규칙 엔진이 짜 준 피드예요. GPT 붙이면 여기 문구가 더 말 잘해요.",
    liveFeedFootnote: "규칙 기반 피드 · GPT 연결 시 같은 자리에 문구만 갈아끼워져요.",
    pickEyebrow: "오늘 픽",
    badgeTodayLocked: "오늘 운동 · 고정됨 — 이제 몸만 움직이면 돼요",
    badgeSessionActive: "세션 진행 중 — 운동 화면에서 세트만 이어서 저장하면 돼요",
    missedHint: "오늘은 아직 미완이에요. 세트 하나만 저장하면 완료로 바뀌어요.",
    decisionEyebrow: "오늘 결정",
    trustTemplate: "신뢰도 {percent}%",
    primaryReasonBadge: "핵심 근거",
    dataBadge: "데이터",
    approxDurationPrefix: "대충",
    chipPlanConfirmed: "오늘 플랜 고정됨",
    chipPickPlan: "아래에서 플랜만 골라 주세요",
    chipSessionLogged: "오늘 세션은 찍혔어요",
    linkWorkoutScreen: "운동 화면 바로가기",
    linkProgram: "프로그램",
    ctaOneMoreSet: "추가로 한 세트 더",
    ctaResumeSession: "세션 이어가기",
    ctaStartWorkout: "운동 시작하기",
    ctaPickPlanFirst: "먼저 아래에서 플랜 정하기",
    linkProgramBrowse: "프로그램 훑기",
    linkReferenceOnly: "참고만 보기",
  },
  todayPlan: {
    statusSuggested: "오늘 결정",
    statusConfirmed: "고정됨",
    statusCompleted: "완료",
    cardHeading: "오늘 운동 플랜",
    confirmedTitle: "오늘 운동 (고정됨)",
    confirmedSubtitle: "— 이대로 가면 돼요",
    estimateLineTemplate: "예상 전체 {duration} · 동작별 합계 약 {minutes}분",
    decisionReasonBadge: "결정 근거",
    btnUsePlan: "오늘 플랜 이대로 쓰기",
    linkChangePlan: "플랜 바꾸기",
    thExercise: "운동",
    thSets: "세트",
    thReps: "횟수",
    thEstimate: "예상",
    rowMinutesSuffix: "분",
    footnoteWhenConfirmed: "고정된 플랜은 그대로 두고 가요. 바꾸고 싶으면 위 「플랜 바꾸기」만 누르면 돼요.",
    hintWhenSuggested: "오늘 할 거 대충 짜 뒀어요. 누르면 ‘추천’ 말고 그냥 오늘 플랜으로 박아 둘게요.",
    hintWhenConfirmed: "고정됐어요. 아래에서 운동만 시작하면 돼요.",
    hintWhenDoneTitle: "오늘 플랜 완료! 수고했어요.",
    hintWhenDoneStreakTemplate: "스트릭 {days}일째 — 오늘도 이어졌어요.",
    footnoteAutoTimeTemplate: "참고: 동작별 시간은 {planLabel} 기준으로 자동 배분한 값이에요.",
  },
  todayStatus: {
    titleEyebrow: "오늘 한 줄 요약",
    loadingMain: "불러오는 중…",
    lineCompleted: "오늘 운동",
    lineCompletedWord: "완료",
    lineActive: "지금",
    lineActiveWord: "운동 중",
    lineMissed: "오늘 운동",
    lineMissedWord: "미완",
    lineBefore: "오늘 운동",
    lineBeforeWord: "전",
    streakEyebrow: "연속 스택",
    streakDaysSuffix: "일",
    recoveryModeBadge: "유지 모드",
    idleNudgeBefore: "아직 시작 전이에요. 플랜만 정한 뒤 ",
    idleNudgeBold: "운동 시작하기",
    idleNudgeAfter: "로 들어가면 돼요.",
    activeNudgeTemplate: "타이머랑 입력은 운동 화면에 있어요. 세트 저장하고 휴식 {seconds}초 쉬었다가 다음 세트로 가면 돼요.",
    missedNudge: "아직 세트가 없어요. 위 리본에서 빠르게 시작하거나, 아래 플랜으로 바로 들어가도 돼요.",
    completedNudge: "주간 목표랑 스트릭 숫자도 갱신됐을 거예요. 성과 탭에서 한번 볼까요.",
    weeklyLoading: "기록 싹 불러오는 중…",
    weeklyProgressTemplate: "이번 주 목표 진행률 {pct}% ({current}/{target}세션)",
    weeklyNoGoalHint: "주간 목표는 아래 「이번 주 목표」에서 슬쩍 정해 두면 돼요.",
    progressAriaLabel: "이번 주 목표 진행률",
  },
  workoutList: {
    eyebrow: "짧게 요약",
    title: "기록 들여다보기",
    subtitle: "볼륨·PR·부위 비중은 저장된 세트를 알아서 묶어서 보여줘요.",
    volumeEyebrow: "누적 볼륨",
    volumeUnitHint: "kg×회×세트 합",
    prEyebrow: "볼륨 PR",
    prCountSuffix: "회",
    prHint: "종목별 최댓값 갈아끼운 횟수",
    rowsEyebrow: "총 세트 행",
    rowsHint: "저장 건수",
    muscleEyebrow: "부위별 볼륨 비중(추정)",
    volumePrefix: "볼륨",
    weightPrefix: "중량",
    deltaFlat: "유지",
    success: "성공",
    fail: "실패",
    delete: "지우기",
    repsSetsTemplate: "{reps}회 × {sets}세트",
    volumeInlinePrefix: "볼륨",
  },
};
